### PR TITLE
eliminate potential bug when using gpcm or nominal

### PR DESCRIPTION
**Pull request by seonghobae**
eliminate potential bug when using gpcm or nominal model
(please check notation of gpcm and nominal model)

### CODE REVIEW

**Comment by philchalmers** [comment]
Was there a real issue with this function that I should be aware of?

**Comment by seonghobae** [comment]
```R
> modScience <- mirt(Science, 1, itemtype = 'gpcm')
Iteration: 50, Log-Lik: -1612.683, Max-Change: 0.00009
> modScience_graded <- mirt(Science, 1)
Iteration: 36, Log-Lik: -1608.870, Max-Change: 0.00010
> MDIFF(modScience)
        MDIFF_1    MDIFF_2   MDIFF_3   MDIFF_4
Comfort       0 -3.7806231 -7.110819 -5.339294
Work          0 -2.4193201 -3.646612 -1.199081
Future        0 -0.9468249 -1.390985 -1.012088
Benefit       0 -4.0059427 -5.532851 -3.285052
> MDIFF(modScience_graded)
           MDIFF_1    MDIFF_2   MDIFF_3
Comfort -4.4820470 -2.4325592 1.3508498
Work    -1.9454671 -0.5995846 1.5080448
Future  -0.9951401 -0.4209051 0.3733599
Benefit -2.7926345 -0.8271576 1.4082456
> 
```

When I use ```MDIFF()``` in context of generalized partial credit model, the difficulty indices were increased for *negative* direction in categorical ordered response like likert style scales.
If theorical assumption is ak0 < ak1 < ak2 < ak3 < ak4, it can be print negative values? I don't think so. If someone's theta value is very low, I have to belive he or she can select a 4th category rely that results? That sounds strange. Or, Am I have miss interpret that results?

Another example is here:

```R
> MDIFF(modCDt_graded) # grm
        MDIFF_1     MDIFF_2     MDIFF_3   MDIFF_4
CD1  -2.3492635 -0.72819709  0.44396747        NA
CD2  -1.8725845 -1.30054182 -0.33717943        NA
CD5  -3.0060010 -1.37822350  0.06416994        NA
CD8  -1.8025443 -0.71451437  1.11102441        NA
CD11 -1.0517544 -0.38305267  0.23165792        NA
CD12 -1.4916276 -0.88012266 -0.14520085 0.8489801
CD14 -1.5092769 -0.59513477  0.09736540 0.8932834
CD15 -2.4143620 -1.21788130 -0.67257629 0.5492597
CD16 -0.5433222 -0.21436272  0.44269488        NA
CD17 -0.4794034 -0.16306492  0.23923655        NA
CD19 -0.8375926  0.08601903  1.06887978        NA
CD21 -1.4895913 -0.83931697 -0.34558622 0.3094819
CD22 -0.5670346 -0.15636442  0.28479609        NA
CD23 -1.4028193 -0.68513250 -0.25786202 0.5645043
CD24 -0.4402705 -0.14360391  0.22456329        NA
CD25 -0.9434336 -0.41580902  0.12043464        NA
> MDIFF(modCDt) # gpcm
     MDIFF_1    MDIFF_2    MDIFF_3    MDIFF_4   MDIFF_5
CD1        0 -2.8397091 -3.7029017 -3.3149265        NA
CD2        0 -1.8451247 -3.8939093 -4.7031905        NA
CD5        0 -2.9513013 -4.4847340 -4.5400572        NA
CD8        0 -1.9384536 -3.1577957 -1.6241978        NA
CD11       0 -1.2110482 -1.6698040 -1.4162117        NA
CD12       0 -1.9358352 -3.2875477 -3.6693206 -2.279337
CD14       0 -1.7291302 -2.4082439 -2.3262049 -1.243515
CD15       0 -3.3758048 -4.5576296 -5.9231437 -5.156356
CD16       0 -0.5933386 -0.9143825 -0.3496219        NA
CD17       0 -0.5217317 -0.7160902 -0.4529703        NA
CD19       0 -0.9189909 -0.8466539  0.3913819        NA
CD21       0 -1.9895640 -3.0835286 -3.6141840 -3.233187
CD22       0 -0.5892423 -0.7600205 -0.4639779        NA
CD23       0 -2.2236025 -3.0877063 -3.6490723 -2.758300
CD24       0 -0.5160403 -0.6922250 -0.4254609        NA
CD25       0 -1.1443675 -1.6679188 -1.5658229        NA
```

**Comment by philchalmers** [comment]
I think you're interpretation is a bit off, multidimensional intercepts and
such are generally in the opposite direction to what you think and are
intended more for a geometric mapping than from anything substantive. MDISC
is however analogous to an unstandardized communality value in linear
factor analysis, but that's about where the usefulness ends.

**Comment by seonghobae** [comment]
Humm. My interest is the *difficulty* parameter ```MDIFF```, not ```MDISC```.

In short, the gpcm or nominal model's d parameter *isn't negative* value in their model. but another model's d parameter *is negative* in each model. In my understanding, -ds/MDISC is for converting d parameter to difficulty statistic negative to positive. But gpcm or nominal model's d parameter *isn't negative*, I was tried to apply *ds/MDISC*, not *-ds/MDISC* when using gpcm/nominal model.

**Comment by seonghobae** [comment]
I have more question: ```MDISC``` isn't useful for evaluate item difficulty in unidimensional model in nomial/gpc model?

**Comment by seonghobae** [comment]
For recently, I studied hard to know item response theory and measurements with having school lectures. After school lectures, I want to make a standard setting with a bookmark method using nominal type items for measuring personality in the industrial psychology setting; like the CRT-A test for assessment aggression. Maybe already you know, bookmark method must require difficulty information from the model.

The CRT-A test's standard settings never tried by psychologists. So, I want to know difficulties each selection (possible answer passages) in each item by ```MDIFF``` for doing standard settings. (application of θ_i = d_j)

If I can, this issue may need to reopen. I tried to estimate item difficulty of nominal scale using O*NET data; parameters of the job. http://www.occupationalinfo.org/appendxb_1.html

```R
> MDIFF(mirt(testCalc6[2:4], 1, itemtype = 'nominal'))
       MDIFF_1   MDIFF_2     MDIFF_3      MDIFF_4    MDIFF_5     MDIFF_6      MDIFF_7   MDIFF_8
Data         0  2.972250  -0.8769796  -0.21710505   1.973060  -0.8677939   0.02927615        NA
People       0 -2.130429  -2.2488380   0.09435517  -2.384953  -0.9942194  -0.34638764        NA
Things       0 -1.649130 -81.5128947 -68.07061662 -47.050804 -53.5856958 -54.81067908 -105.7549
```

In above result, The 8th passage (```MDIFF_8```; Precision Working) in 'Things' item has to minus value and 1st passage (```MDIFF_1```; Feeding-Offbearing) has to 0. Theoretically, ```MDIFF_8``` is a most advanced technique for handling 'Things' in jobs, and ```MDIFF_1``` is the easiest technique for handling 'Things'. By the theory, ```MDIFF_8``` isn't the easiest.

So I tried change minus to plus and plus to minus for getting correct difficulties. Finally, I solve it. Is it a bad idea for preparing standard settings by bookmark method?

```R
> MDIFF(mirt(testCalc6[2:4], 1, itemtype = 'nominal'))*-1
      MDIFF_1   MDIFF_2    MDIFF_3     MDIFF_4   MDIFF_5    MDIFF_6     MDIFF_7  MDIFF_8
Data         0 -2.972250  0.8769796  0.21710505 -1.973060  0.8677939 -0.02927615       NA
People       0  2.130429  2.2488380 -0.09435517  2.384953  0.9942194  0.34638764       NA
Things       0  1.649130 81.5128947 68.07061662 47.050804 53.5856958 54.81067908 105.7549
```

Sincerely,
Seongho

**Comment by seonghobae** [comment]
## NOTE
The Calculation of MDIFF & MDISC in 2PL Partial Credit Model (2PPC): http://www.bmirt.com/media/5becaf7f7a11907fffff8352ffffd502.pdf

**Comment by philchalmers** [comment]
Neat, thanks. It looks like the PCM format they use is very different than mirt, so some analytical translating will have to be done to make it compatible. But it's good to know that something exists. Added to the TODO list.

**Pull request closed without merging**
