### PR TITLE
added grsmIRT and tests

### PR DESCRIPTION
**Pull request by superpowerkkh**

### CODE REVIEW

**Comment by philchalmers** [comment]
I'm away for the next few days, but I'll review this code when I return. Thanks.

**Comment by superpowerkkh** [comment]
Okay, I change a little bit, not much...
About the starting values, since grsmIRT is the same the graded except for the location parameter and  the different than intercept parameters(threshold?)... How about just setting location parameters all 0 and changing for lambdas... so I think something like val <- c(lambdas[,i], zetas[[i]]/lambdas[i,], 0) (in LoadPars.R) would suffice... even though I couldn't fully understand the reasons for setting up for lambdas and zetas... (It seems different than the recommendation from Urry(1974).

And thank you for letting me in as a contributor... I am honored... Actually I implemented another model for extreme response tendencies but I think it's better to pull it at another time... peace...

Urry, V. W. (1974). Approximations to Item Parameters of Mental Test Models and Their Uses1. Educational and Psychological Measurement, 34(2), 253-269.

**Comment by philchalmers** [comment]
You'll notice now that the constraints are applied automatically, so I updated your tests accordingly. Now it has the same form as the 'grsm' input type.

**Comment by superpowerkkh** [comment]
Great. I appreciate your effort.
2015. 12. 19. 오전 5:21에 "Phil Chalmers" <notifications@github.com>님이 작성:

**Pull request merged**
